version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: ringle-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ringle-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ringle-app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_DOCKER_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
